.github/workflows/deploy.yml
=> fix: Add auto-publish of casnode website

.github/workflows/deploy.yml, .gitignore, crowdin.yml, package.json
=> fix: Setup Crowdin integration for Casnode-website

docusaurus.config.js
=> feat: Optimize website pages.

docs/architecture-overview.md, docs/controllers.md, docs/main-package.md, docs/routers.md, sidebars.js
Part of: https://github.com/casbin/casnode/issues/304
=> feat: add architecture overview, main-package, routers, controllers

docusaurus.config.js
=> fix: Fix broken edit links

docusaurus.config.js
=> feat: Add help translate and fix Japanese translation

docs/BTpanel.md, docs/installation.md, sidebars.js
=> feat: add installation by BT panel

docs/BTpanel.md
=> fix: add .  and remove / in BTpanel.md

docs/Docker.md, docs/installation.md, sidebars.js
Fix: https://github.com/casbin/casnode/issues/133
=> add installation by docker

README.md, docs/BTpanel.md, docs/architecture-overview.md, docs/controllers.md, docs/installation.mdx, docs/intro.md, docs/main-features.md, docs/main-package.md, docs/routers.md, yarn.lock
=> docs: Add more content and optimize docs

docusaurus.config.js
=> feat: Add sitemap

package.json, yarn.lock
=> feat: Update docusaurus to beta4

docusaurus.config.js
=> feat: Add algolia docsearch

docs/Docker.md
=> fix: add docker tip

crowdin.yml
=> fix: Update Crowdin project

docs/Docker.md
=> feat: add installation tip

src/components/BrowserWindow/index.js, src/components/BrowserWindow/styles.module.css, src/pages/index.js, src/pages/index.module.css
=> feat: Add Casnode iframe to page

src/components/BrowserWindow/styles.module.css, src/pages/index.js, src/pages/index.module.css
=> feat: Add more Casnode iframes in page

src/components/HomepageFeatures.js, src/pages/index.js
=> feat: Add homepage translate

docusaurus.config.js, src/pages/help.js, src/pages/index.js, src/pages/index.module.scss
=> feat: Add help page

package.json, yarn.lock
=> build: Update Docusaurus

package.json, src/theme/DocItem/index.js, src/theme/DocItem/styles.module.css, yarn.lock
=> feat: Add Disqus

crowdin.yml
=> fix: Change Crowdin project

package.json, yarn.lock
=> fix: Update Docusaurus

docs/main-features.md, docs/server-side-rendering.md, sidebars.js
Fix: https://github.com/casbin/casnode/issues/425
=> feat:add more explanation of ssr

README.md, docs/internationalization.md, docs/main-features.md, docusaurus.config.js
similar to https://github.com/casbin/casbin-website-v2/pull/79
=> feat: Edit this page will jump to Crowdin when using non-English

docs/api-overview.md, docs/architecture-overview.md, docs/bt-panel.md, docs/controllers.md, docs/docker.md, docs/installation.mdx, docs/internationalization.md, docs/main-features.md, docs/main-package.md, docs/migration.md, docs/overview.md, docs/routers.md, docs/server-side-rendering.md, docusaurus.config.js, sidebars.js
=> feat: Improve SEO

.eslintignore, .eslintrc, .husky/pre-commit, .stylelintignore, .stylelintrc.json, babel.config.js, docusaurus.config.js, package.json, sidebars.js, src/components/BrowserWindow/index.js, src/components/BrowserWindow/styles.module.css, src/components/HomepageFeatures.js, src/css/custom.css, src/pages/help.js, src/pages/index.js, src/pages/index.module.scss, src/theme/DocPaginator/index.js, static/js/gitter.js, static/js/tawk.js, yarn.lock
Similar for: https://github.com/casdoor/casdoor-website/issues/322
=> feat: Add eslint and stylelint

sidebars.js
like: https://github.com/casdoor/casdoor-website/pull/341
https://deploy-preview-67--casnode.netlify.app/docs/category/getting-started
=> feat: generate index page for categories

src/pages/index.js, src/pages/index.module.scss
=> feat: mobile adaptation

package.json, yarn.lock
https://github.com/facebook/docusaurus/releases/tag/v2.2.0
=> chore: upgrade docusaurus to 2.2.0

README.md, docs/api-overview.md, docs/architecture-overview.md, docs/bt-panel.md, docs/controllers.md, docs/docker.md, docs/installation.mdx, docs/internationalization.md, docs/main-features.md, docs/main-package.md, docs/migration.md, docs/overview.md, docs/routers.md, docs/server-side-rendering.md, docusaurus.config.js, src/theme/DocItem/Footer/index.js, src/theme/DocItem/Footer/styles.module.css
https://github.com/casdoor/casdoor-website/pull/391
https://github.com/casdoor/casdoor-website/pull/410
=> refactor: show authors instead of last updated

docusaurus.config.js, src/components/BrowserWindow/index.js, src/components/CasnodeCard/index.js, src/components/NavbarItems/Casdoor.js, src/pages/index.js
=> refactor: use the single demo site

.github/workflows/docs-links-check-pr.yml, docs/overview.md, i18n/de/docusaurus-plugin-content-docs/current/intro.md, i18n/de/docusaurus-plugin-content-docs/current/overview.md, i18n/fr/docusaurus-plugin-content-docs/current/overview.md, i18n/ja/docusaurus-plugin-content-docs/current/overview.md, i18n/ko/docusaurus-plugin-content-docs/current/overview.md, i18n/ru/docusaurus-plugin-content-docs/current/overview.md, i18n/zh/docusaurus-plugin-content-docs/current/overview.md
fix: https://github.com/casnode/casnode-website/actions/runs/5298048067/jobs/9590194297
=> docs: fix dead links
